behaviors:
  TankLearning:
    behavioral_cloning: null
    checkpoint_interval: 500000
    hyperparameters: {batch_size: 128, beta: 0.01, buffer_size: 10240, epsilon: 0.2,
      lambd: 0.95, learning_rate: 0.0001, learning_rate_schedule: linear, num_epoch: 4}
    init_path: null
    keep_checkpoints: 5
    max_steps: 25000000
    network_settings: {hidden_units: 256, memory: null, normalize: true, num_layers: 2,
      vis_encode_type: simple}
    reward_signals:
      curiosity: {encoding_size: 64, gamma: 0.99, learning_rate: 0.0003, strength: 0.07}
      extrinsic: {gamma: 0.99, strength: 1.0}
    self_play: {initial_elo: 17252.0, play_against_latest_model_ratio: 0.5, save_steps: 10000,
      swap_steps: 10000, team_change: 50000, window: 10}
    summary_freq: 10000
    threaded: true
    time_horizon: 128
    trainer_type: ppo
checkpoint_settings: {force: false, inference: false, initialize_from: null, load_model: false,
  resume: true, run_id: equipos3, train_model: false}
debug: false
engine_settings: {capture_frame_rate: 60, height: 84, no_graphics: false, quality_level: 5,
  target_frame_rate: -1, time_scale: 20, width: 84}
env_settings: {base_port: 5005, env_args: null, env_path: /home/daniel/Escritorio/TFG/tanks.x86_64,
  num_envs: 10, seed: -1}
environment_parameters:
  obstacles:
    curriculum:
    - completion_criteria: null
      name: obstacles
      value:
        sampler_parameters: {seed: 9116, value: 1}
        sampler_type: constant
  team_0_number:
    curriculum:
    - completion_criteria: null
      name: team_0_number
      value:
        sampler_parameters: {seed: 9115, value: 3}
        sampler_type: constant
  team_1_number:
    curriculum:
    - completion_criteria: null
      name: team_1_number
      value:
        sampler_parameters: {seed: 9114, value: 3}
        sampler_type: constant
